export const ADD_MEDICATION = "ADD_MEDICATION";
export const UPDATE_MEDICATION = "UPDATE_MEDICATION";
export const DELETE_MEDICATION = "DELETE_MEDICATION";
export const RESET_MEDICATIONS = "RESET_MEDICATIONS";
