export const ADD_M_ID = "ADD_M_ID";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_NOTIFICATIONS_ID = "DELETE_NOTIFICATIONS_ID";
export const GET_DATA = "GET_DATA";
