export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const IS_LOADING_NOTIFICATIONS = "IS_LOADING_NOTIFICATIONS";
